

name: CI - Python Project - Webservice

on:
  push:

jobs:

  init_env:
    runs-on: ubuntu-latest
    name: Initilize run environement
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        run: echo Checkout complete ... 
      - name: Running init command
        run: | 
          make init
          echo Init completed
  
  test:
    runs-on: ubuntu-latest
    name: Testing and Benchmarking
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        run: echo Checkout complete ... 
      - name: Running test command
        run: make test
      - name: Running benchmark command
        run: make benchmark
  
  start:
    runs-on: ubuntu-latest
    name: Starting Server
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        run: echo Checkout complete ... 
      - name: Starting
        run: make run
